// Image RPC fields from iSulad v2.1.5 images.proto.
syntax = "proto3";
package images;

import "google/protobuf/timestamp.proto";

service ImagesService {
    rpc List(ListImagesRequest) returns (ListImagesResponse);
    rpc Delete(DeleteImageRequest) returns (DeleteImageResponse);
    rpc Load(LoadImageRequest) returns (LoadImageResponse);
    rpc Import(ImportRequest) returns (ImportResponse);
    rpc PullImage(PullImageRequest) returns (stream PullImageResponse);
}

message Descriptor {
    string digest = 2;
    int64 size = 3;
}

message Image {
    string name = 1;
    Descriptor target = 3;
    google.protobuf.Timestamp created_at = 4;
}

message ListImagesRequest {
    map<string, string> filters = 1;
}

message ListImagesResponse {
    repeated Image images = 1;
    uint32 cc = 2;
    string errmsg = 3;
}

message LoadImageRequest {
    string file = 1;
    string type = 2;
    string tag = 3;
}

message LoadImageResponse {
    uint32 cc = 1;
    string errmsg = 2;
}

message ImportRequest {
    string file = 1;
    string tag = 2;
}

message ImportResponse {
    string id = 1;
    uint32 cc = 2;
    string errmsg = 3;
}

message ImageSpec {
    string image = 1;
    map<string, string> annotations = 2;
}

message AuthConfig {
    string username = 1;
    string password = 2;
}

message PullImageRequest {
    ImageSpec image = 1;
    AuthConfig auth = 2;
    bool is_progress_visible = 3;
}

message PullImageResponse {
    string image_ref = 1;
    string stream = 2;
    bytes progress_data = 3;
}

message DeleteImageRequest {
    string name = 1;
    bool force = 2;
}

message DeleteImageResponse {
    string name = 1;
    uint32 cc = 2;
    string errmsg = 3;
}
